### ISSUE TITLE
Facility for admin user to add / remove items

### ISSUE THREAD

**Issue by trevorparsons** [ecostanza/fareshares#1]
A frequent complaint about the predecessor system was that if a Fareshares volunteer wanted to add or remove a product from the price list, they would have to send a request the developer / maintainer of the application.

In due course, it would be great if an admin user could do this job themselves.

Just an idea. No pressure or expectation.

And thanks for your fantastic work, Enrico! :-)

**Comment by ecostanza** [comment]
Indeed this is part of the current version (just not visible to all users)
